package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.Good;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    Good selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    List<Good> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int updateByPrimaryKey(Good record);

    List<Good> getGoodsByCondition(@Param("typeOneId")Integer typeOneId, @Param("typeTwoId") Integer typeTwoId, @Param("brandId") Integer brandId, @Param("goodName") String goodName);

    int deleteGoods(@Param("ids")List<Integer> delTds);

    int deleteById(@Param("ids")Integer id);

    int insertGood(Good good);

    Good selectByGoodId(Integer id);


    int updateByPrimaryKey1(Good newGood);

    Long getCount();

    List<Good> getNewGoodsList();

    List<Good> getMoreGoodsList();

    List<Good> getAboutGoodsList(@Param("goodType")Integer goodType);
}