package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    int updateByPrimaryKey(Order record);

    List<Order> getOrdersByCondition(Integer userId);


    int chartAdd(Order order);

    int deleteByPrimaryKey1(String ids);

    List<Order> selectByUserIdAndGoodId(@Param("userId")Integer userId, @Param("goodId")Integer goodId);

    int qualityReduces(@Param("ids")String ids,@Param("count")Integer count);

    int qualityAdds(@Param("ids")String ids,@Param("count")Integer count);
}