package cn.edu.hzvtc.pojo;

public class Good {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsname
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String goodName;

    public String getGoodName() {
        return goodName;
    }

    public void setGoodName(String goodName) {
        this.goodName = goodName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.number
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.image
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String goodImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer goodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer goodPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.stock
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String description;

    private Integer goodDelState;

    public Good(Integer goodId, String goodName,  String goodImage, Integer goodType, Integer goodPrice, Integer stock, String description, Integer goodDelState) {
        this.goodId = goodId;
        this.goodName = goodName;
        this.goodImage = goodImage;
        this.goodType = goodType;
        this.goodPrice = goodPrice;
        this.stock = stock;
        this.description = description;
        this.goodDelState = goodDelState;
    }

    public Good() {
    }

    public Integer getGoodId() {
        return goodId;
    }

    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    public String getGoodImage() {
        return goodImage;
    }

    public void setGoodImage(String goodImage) {
        this.goodImage = goodImage;
    }

    public Integer getGoodType() {
        return goodType;
    }

    public void setGoodType(Integer goodType) {
        this.goodType = goodType;
    }

    public Integer getGoodPrice() {
        return goodPrice;
    }

    public void setGoodPrice(Integer goodPrice) {
        this.goodPrice = goodPrice;
    }

    public Integer getGoodDelState() {
        return goodDelState;
    }

    public void setGoodDelState(Integer goodDelState) {
        this.goodDelState = goodDelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Id
     *
     * @return the value of goods.Id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */



    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.stock
     *
     * @param stock the value for goods.stock
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
    private GoodsType goodsType;

    public Good(Integer goodId, String goodName,  String goodImage, Integer goodType, Integer goodPrice, Integer stock, String description, Integer goodDelState, GoodsType goodsType) {
        this.goodId = goodId;
        this.goodName = goodName;
        this.goodImage = goodImage;
        this.goodType = goodType;
        this.goodPrice = goodPrice;
        this.stock = stock;
        this.description = description;
        this.goodDelState = goodDelState;
        this.goodsType = goodsType;
    }

    public GoodsType getGoodsType() {
        return goodsType;
    }

    public void setGoodsType(GoodsType goodsType) {
        this.goodsType = goodsType;
    }

    @Override
    public String toString() {
        return "Good{" +
                "goodId=" + goodId +
                ", goodName='" + goodName + '\'' +
                ", goodImage='" + goodImage + '\'' +
                ", goodType='" + goodType + '\'' +
                ", goodPrice=" + goodPrice +
                ", stock=" + stock +
                ", description='" + description + '\'' +
                ", goodDelState=" + goodDelState +
                '}';
    }
}