package cn.edu.hzvtc.pojo;

import java.util.Date;

public class Order {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_number
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_good_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderGoodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Date orderOperatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.quality
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer orderDelState;

    private Good goodInfo;
    private User userInfo;

    public Order(Integer orderId, Integer orderNumber, Integer orderGoodId, Integer orderUserId, Date orderOperatorTime, Integer quality, Integer orderState, Integer orderDelState, Good goodInfo, User userInfo) {
        this.orderId = orderId;
        this.orderNumber = orderNumber;
        this.orderGoodId = orderGoodId;
        this.orderUserId = orderUserId;
        this.orderOperatorTime = orderOperatorTime;
        this.quality = quality;
        this.orderState = orderState;
        this.orderDelState = orderDelState;
        this.goodInfo = goodInfo;
        this.userInfo = userInfo;
    }

    public Order() {
    }

    public Good getGoodInfo() {
        return goodInfo;
    }

    public void setGoodInfo(Good goodInfo) {
        this.goodInfo = goodInfo;
    }

    public User getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(User userInfo) {
        this.userInfo = userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_number
     *
     * @return the value of orders.order_number
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_number
     *
     * @param orderNumber the value for orders.order_number
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_good_id
     *
     * @return the value of orders.order_good_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderGoodId() {
        return orderGoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_good_id
     *
     * @param orderGoodId the value for orders.order_good_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderGoodId(Integer orderGoodId) {
        this.orderGoodId = orderGoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_user_id
     *
     * @return the value of orders.order_user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_user_id
     *
     * @param orderUserId the value for orders.order_user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_operator_time
     *
     * @return the value of orders.order_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Date getOrderOperatorTime() {
        return orderOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_operator_time
     *
     * @param orderOperatorTime the value for orders.order_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderOperatorTime(Date orderOperatorTime) {
        this.orderOperatorTime = orderOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.quality
     *
     * @return the value of orders.quality
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.quality
     *
     * @param quality the value for orders.quality
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setQuality(Integer quality) {
        this.quality = quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_state
     *
     * @return the value of orders.order_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_state
     *
     * @param orderState the value for orders.order_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_del_state
     *
     * @return the value of orders.order_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getOrderDelState() {
        return orderDelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_del_state
     *
     * @param orderDelState the value for orders.order_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setOrderDelState(Integer orderDelState) {
        this.orderDelState = orderDelState;
    }

    @Override
    public String toString() {
        return "Order{" +
                "orderId=" + orderId +
                ", orderNumber=" + orderNumber +
                ", orderGoodId=" + orderGoodId +
                ", orderUserId=" + orderUserId +
                ", orderOperatorTime=" + orderOperatorTime +
                ", quality=" + quality +
                ", orderState=" + orderState +
                ", orderDelState=" + orderDelState +
                ", goodInfo=" + goodInfo +
                ", userInfo=" + userInfo +
                '}';
    }
}