package cn.edu.hzvtc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date userOperatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_type
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_comment_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_announce_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userAnnounceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    private Integer userDelState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_operator_time
     *
     * @return the value of users.user_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Date getUserOperatorTime() {
        return userOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_operator_time
     *
     * @param userOperatorTime the value for users.user_operator_time
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserOperatorTime(Date userOperatorTime) {
        this.userOperatorTime = userOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_type
     *
     * @return the value of users.user_type
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_type
     *
     * @param userType the value for users.user_type
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_order_id
     *
     * @return the value of users.user_order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserOrderId() {
        return userOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_order_id
     *
     * @param userOrderId the value for users.user_order_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserOrderId(Integer userOrderId) {
        this.userOrderId = userOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_comment_id
     *
     * @return the value of users.user_comment_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserCommentId() {
        return userCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_comment_id
     *
     * @param userCommentId the value for users.user_comment_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserCommentId(Integer userCommentId) {
        this.userCommentId = userCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_announce_id
     *
     * @return the value of users.user_announce_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserAnnounceId() {
        return userAnnounceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_announce_id
     *
     * @param userAnnounceId the value for users.user_announce_id
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserAnnounceId(Integer userAnnounceId) {
        this.userAnnounceId = userAnnounceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_del_state
     *
     * @return the value of users.user_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public Integer getUserDelState() {
        return userDelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_del_state
     *
     * @param userDelState the value for users.user_del_state
     *
     * @mbg.generated Wed Feb 24 17:04:42 CST 2021
     */
    public void setUserDelState(Integer userDelState) {
        this.userDelState = userDelState;
    }
}